version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-exercise
    environment:
      - POSTGRES_USER=diego
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=materiales
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data